# Testing PR comments

name: pr_comment_log_info

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_info_log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: find all added or modified info logs
        run: |
          echo "Some changes"


      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            log.info() ============